<?php

namespace PPE\GSBBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CollaborateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollaborateurRepository extends EntityRepository
{
	public function findOneByUsername($username)
	{
		$nompren = preg_split("/\./", $username);
		$prenom = $nompren[0];
		$nom = $nompren[1];
		
		$q = $this
		->createQueryBuilder('u')
		->where('u.nomCol = :nom AND u.prenomCol = :prenom')
		->setParameter('nom', $nom)
		->setParameter('prenom', $prenom)
		->getQuery();
		
		try
		{
			$user = $q->getSingleResult();
		}
		catch (NoResultException $e)
		{
			throw new UsernameNotFoundException(sprintf('Unable to find an active admin AcmeUserBundle:User object identified by "%s".', $username), 0, $e);
		}
		
		return $user;
	}
}
