ppegsb_homepage:
    pattern:  /Index
    defaults: { _controller: PPEGSBBundle:Default:index }

ppegsb_newFicheRp:
    pattern:  /RP/new
    defaults: { _controller: PPEGSBBundle:Default:ficheRp}

ppegsb_getFicheRp:
    pattern:  /RP/get-{id}
    defaults: { _controller: PPEGSBBundle:Default:getRp}





ppegsb_listePra:
    pattern: /Praticien/Liste
    defaults: { _controller: PPEGSBBundle:Default:listePra }

ppegsb_fichePra:
    pattern:  /Praticien/Fiche-{id}
    defaults: { _controller: PPEGSBBundle:Default:fichePra }
    requirements: {id: \d+}

ppegsb_mapPra:
    pattern: /Praticien/map
    defaults: { _controller: PPEGSBBundle:Default:mapPra}

ppegsb_mapPra:
    pattern: /Praticien/map
    defaults: { _controller: PPEGSBBundle:Default:mapPra}


ppegsb_listeMed:
    pattern: /Medicament/Liste
    defaults: { _controller: PPEGSBBundle:Default:listeMed }

ppegsb_ficheMed:
    pattern:  /Medicament/Fiche-{id}
    defaults: { _controller: PPEGSBBundle:Default:ficheMed }


ppegsb_connexion:
    pattern:  /Connexion
    defaults: { _controller: PPEGSBBundle:Default:connexion }


ppegsb_login:
    pattern:  /login
    defaults: { _controller: PPEGSBBundle:Security:login }

ppegsb_logincheck:
    pattern:  /login_check

ppegsb_logout:
    pattern:  /logout

ppegsb_admin:
    pattern:  /admin
    defaults: { _controller: PPEGSBBundle:Default:admin }
