PPE\GSBBundle\Entity\Composant:
    type: entity
    table: COMPOSANT
    id:
        codeComp:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: code_comp
            generator:
                strategy: IDENTITY
    fields:
        libelleComp:
            type: string
            nullable: false
            length: 250
            fixed: false
            column: libelle_comp
    manyToMany:
        depotLegalConstituer:
            targetEntity: Medicament
            cascade: {  }
            mappedBy: codeComp
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
