PPE\GSBBundle\Entity\Calendrier:
    type: entity
    table: CALENDRIER
    id:
        jjmmaaaaDeb:
            type: datetime
            nullable: false
            id: true
            column: JJMMAAAA_DEB
            generator:
                strategy: IDENTITY
    lifecycleCallbacks: {  }
