PPE\GSBBundle\Entity\Collaborateur:
    type: entity
    table: COLLABORATEUR
    id:
        matriculeCol:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: matricule_col
            generator:
                strategy: IDENTITY
    fields:
        nomCol:
            type: string
            nullable: false
            length: 25
            fixed: false
            column: nom_col
        prenomCol:
            type: string
            nullable: false
            length: 25
            fixed: false
            column: prenom_col
        adresseCol:
            type: string
            nullable: false
            length: 50
            fixed: false
            column: adresse_col
        cpCol:
            type: string
            nullable: false
            length: 5
            fixed: false
            column: cp_col
        mdpCol:
            type: string
            nullable: false
            length: 350
            fixed: false
            column: mdp_col
        dateEmbauche:
            type: datetime
            nullable: false
            column: date_embauche
        villeCol:
            type: string
            nullable: false
            length: 50
            fixed: false
            column: ville_col
        saltCol:
            type: string
            nullable: false
            length: 350
            fixed: false
            column: salt_col
    manyToMany:
        numAct:
            targetEntity: ActiviteComplementaire
            cascade: {  }
            mappedBy: null
            inversedBy: matriculeColOrg
            joinTable:
                name: organise
                joinColumns:
                    -
                        name: matricule_col_org
                        referencedColumnName: matricule_col
                inverseJoinColumns:
                    -
                        name: num_act
                        referencedColumnName: num_act
            orderBy: null
    lifecycleCallbacks: {  }
