PPE\GSBBundle\Entity\Commune:
    type: entity
    table: COMMUNE
    indexes:
        IDX_DDA72FF41030639A:
            columns:
                - code_dep
    id:
        codeCommune:
            type: string
            nullable: false
            length: 25
            fixed: false
            id: true
            column: code_commune
            generator:
                strategy: IDENTITY
    fields:
        libelleCommun:
            type: string
            nullable: false
            length: 25
            fixed: false
            column: libelle_commun
    manyToOne:
        codeDep:
            targetEntity: Departement
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                code_dep:
                    referencedColumnName: code_dep
            orphanRemoval: false
    lifecycleCallbacks: {  }
