PPE\GSBBundle\Entity\EtreResponsable:
    type: entity
    table: ETRE_RESPONSABLE
    indexes:
        IDX_2087271E875E4B76:
            columns:
                - matricule_col_etr
        IDX_2087271E8602054F:
            columns:
                - JJMMAAAA_DEB
        IDX_2087271EB8E26183:
            columns:
                - code_secteur
    id: {  }
    fields:
        jjmmaaaaFin:
            type: datetime
            nullable: false
            column: JJMMAAAA_FIN
    oneToOne:
        matriculeColEtr:
            targetEntity: Collaborateur
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                matricule_col_etr:
                    referencedColumnName: matricule_col
            orphanRemoval: false
        jjmmaaaaDeb:
            targetEntity: Calendrier
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                JJMMAAAA_DEB:
                    referencedColumnName: JJMMAAAA_DEB
            orphanRemoval: false
        codeSecteur:
            targetEntity: Secteur
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                code_secteur:
                    referencedColumnName: code_secteur
            orphanRemoval: false
    lifecycleCallbacks: {  }
