PPE\GSBBundle\Entity\Famille:
    type: entity
    table: FAMILLE
    id:
        codeFamille:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: code_famille
            generator:
                strategy: IDENTITY
    fields:
        libelleFamille:
            type: string
            nullable: false
            length: 250
            fixed: false
            column: libelle_famille
    lifecycleCallbacks: {  }
