PPE\GSBBundle\Entity\Motif:
    type: entity
    table: MOTIF
    id:
        codeMotif:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: code_motif
            generator:
                strategy: IDENTITY
    fields:
        libelleMotif:
            type: string
            nullable: false
            length: 250
            fixed: false
            column: libelle_motif
    lifecycleCallbacks: {  }
