PPE\GSBBundle\Entity\Presentation:
    type: entity
    table: PRESENTATION
    id:
        codePresent:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: code_present
            generator:
                strategy: IDENTITY
    fields:
        libellePresent:
            type: string
            nullable: false
            length: 25
            fixed: false
            column: libelle_present
        depotLegalPresent:
            type: string
            nullable: false
            length: 25
            fixed: false
            column: depot_legal_present
    lifecycleCallbacks: {  }
