PPE\GSBBundle\Entity\Remplace:
    type: entity
    table: REMPLACE
    indexes:
        IDX_92BF0EDE8A7617B8:
            columns:
                - matricule_praticien_remplace
        IDX_92BF0EDE4509622E:
            columns:
                - matricule_praticien_remplacant
        IDX_92BF0EDE94E879DC:
            columns:
                - JJMMAAAA
    id: {  }
    oneToOne:
        matriculePraticienRemplace:
            targetEntity: Praticien
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                matricule_praticien_remplace:
                    referencedColumnName: matricule_praticien
            orphanRemoval: false
        matriculePraticienRemplacant:
            targetEntity: Praticien
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                matricule_praticien_remplacant:
                    referencedColumnName: matricule_praticien
            orphanRemoval: false
        jjmmaaaa:
            targetEntity: Date
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                JJMMAAAA:
                    referencedColumnName: JJMMAAAA
            orphanRemoval: false
    lifecycleCallbacks: {  }
