PPE\GSBBundle\Entity\ResponsableDeSecteur:
    type: entity
    table: RESPONSABLE_DE_SECTEUR
    id: {  }
    oneToOne:
        matriculeColRes:
            targetEntity: Collaborateur
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                matricule_col_res:
                    referencedColumnName: matricule_col
            orphanRemoval: false
    lifecycleCallbacks: {  }
