PPE\GSBBundle\Entity\Secteur:
    type: entity
    table: SECTEUR
    id:
        codeSecteur:
            type: string
            nullable: false
            length: 1
            fixed: false
            id: true
            column: code_secteur
            generator:
                strategy: IDENTITY
    fields:
        libelleSecteur:
            type: string
            nullable: false
            length: 50
            fixed: false
            column: libelle_secteur
    lifecycleCallbacks: {  }
