PPE\GSBBundle\Entity\Specialite:
    type: entity
    table: SPECIALITE
    id:
        codeSpec:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: code_spec
            generator:
                strategy: IDENTITY
    fields:
        libelleSpec:
            type: string
            nullable: false
            length: 250
            fixed: false
            column: libelle_spec
    manyToMany:
        matriculePraticien:
            targetEntity: Praticien
            cascade: {  }
            mappedBy: null
            inversedBy: codeSpec
            joinTable:
                name: posseder
                joinColumns:
                    -
                        name: code_spec
                        referencedColumnName: code_spec
                inverseJoinColumns:
                    -
                        name: matricule_praticien
                        referencedColumnName: matricule_praticien
            orderBy: null
    lifecycleCallbacks: {  }
