PPE\GSBBundle\Entity\TypeIndividu:
    type: entity
    table: TYPE_INDIVIDU
    id:
        codeIndividu:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: code_individu
            generator:
                strategy: IDENTITY
    fields:
        libelleIndividu:
            type: string
            nullable: false
            length: 250
            fixed: false
            column: libelle_individu
    lifecycleCallbacks: {  }
