PPE\GSBBundle\Entity\TypeFrais:
    type: entity
    table: TYPE_FRAIS
    id:
        tfCode:
            type: string
            nullable: false
            length: 25
            fixed: false
            id: true
            column: tf_Code
            generator:
                strategy: IDENTITY
    fields:
        tfLibelle:
            type: string
            nullable: true
            length: 25
            fixed: false
            column: tf_libelle
        tfForfait:
            type: string
            nullable: true
            length: 25
            fixed: false
            column: tf_forfait
    manyToMany:
        ffMois:
            targetEntity: FicheFrais
            cascade: {  }
            mappedBy: tfCode
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
